(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> Adapter not found for google:sql"
p3
sS'layer'
p4
S'/opt/web2py/applications/datalake/models/db.py'
p5
sS'code'
p6
S'<code object <module> at 0x7ff5e4cd7330, file "/opt/web2py/applications/datalake/models/db.py", line 7>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/opt/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/opt/web2py/applications/datalake/models/db.py", line 36, in <module>\n    check_reserved=[\'all\'])\n  File "/opt/web2py/gluon/packages/dal/pydal/base.py", line 171, in __call__\n    obj = super(MetaDAL, cls).__call__(*args, **kwargs)\n  File "/opt/web2py/gluon/packages/dal/pydal/base.py", line 456, in __init__\n    adapter = adapters.get_for(self._dbname)\n  File "/opt/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 19, in get_for\n    \'Adapter not found for %s\' % uri\nSyntaxError: Adapter not found for google:sql\n'
p11
s.